public with sharing class calculator {
    public calculator() {

        String a = 'abc';
        String b = 'bcd';
    }

    public static void add() {
        System.debug('Addition of two numbers is here to be done and aa');
    }

    public static void sub() {
        System.debug('sub');
    }

    public static void div() {
        System.debug('Addition of two numbers is here to be done and aa');
    }

    public static void mul() {
        System.debug('sub');
    }
}